### ISSUE TITLE
Using mod() in line 50:  pylibs/Scripts/gen_hycom_3Dth.py 

### ISSUE THREAD

**Issue by huyquangtranaus** [wzhengui/pylibs#1]
Hi @wzhengui 

I have a quick look at your pylibs repo. It  looks cool. Thanks for sharing it :)

It seems to me that we don't need to use mod on line 50:  sx=mod(array(C.variables['lon'][:])+360,360)-360 when the latitude is positive.  This is the case for Australia/NewZealand.

For example: 

I have: sx  = array(C.variables['lon'][:]) 

sx =[143.04003906 143.11999512 143.19995117 143.2800293  143.35998535
 143.43994141 143.52001953 143.59997559 143.67993164 143.76000977
 143.83996582 143.92004395 144.         144.07995605 144.16003418
 144.23999023 144.32006836 144.40002441 144.47998047 144.56005859
 144.64001465 144.7199707  144.80004883 144.88000488 144.95996094
 145.04003906 145.11999512 145.19995117 145.2800293  145.35998535
 145.43994141 145.52001953 145.59997559 145.67993164 145.76000977
 145.83996582 145.92004395 146.         146.07995605 146.16003418
 146.23999023 146.32006836 146.40002441]

If I use: sx=mod(array(C.variables['lon'][:])+360,360)-360

sx = [-216.95996094 -216.88000488 -216.80004883 -216.7199707  -216.64001465
 -216.56005859 -216.47998047 -216.40002441 -216.32006836 -216.23999023
 -216.16003418 -216.07995605 -216.         -215.92004395 -215.83996582
 -215.76000977 -215.67993164 -215.59997559 -215.52001953 -215.43994141
 -215.35998535 -215.2800293  -215.19995117 -215.11999512 -215.04003906
 -214.95996094 -214.88000488 -214.80004883 -214.7199707  -214.64001465
 -214.56005859 -214.47998047 -214.40002441 -214.32006836 -214.23999023
 -214.16003418 -214.07995605 -214.         -213.92004395 -213.83996582
 -213.76000977 -213.67993164 -213.59997559]

Cheers,
Huy

**Comment by wzhengui** [comment]
Hi Huy:

Thank you for reporting this bug to me. I just fixed it. I noticed this bug
some time ago, and got it fixed in gen_hycom_hotstart.py, but forgot this
script.

Thanks,
Zhengui

**Comment by huyquangtranaus** [comment]
No worries @wzhengui 

Have you also changed line 34:  sx=mod(array(C.variables['lon'][:])+360,360)-360   in Scripts/gen_hycom_hotstart.py?

Cheers,
Huy

**Comment by wzhengui** [comment]
It was changed before.  it should work as long as lxi and sx are
consistent. Zhengui

**Comment by huyquangtranaus** [comment]
No worries mate.  Cheers, Huy.
