### ISSUE TITLE
Nan values in major tidal consitudents

### ISSUE THREAD

**Issue by huyquangtranaus** [wzhengui/pylibs#4]
[gen_bctides.py](https://github.com/wzhengui/pylibs/blob/44f9fd07a8894bef78c7f3eb56131a8f122949b9/pyScripts/gen_bctides.py)

Hi @wzhengui your gen_bctides.py to generate bctides.in from FES2014 looks great. I've tried it, but got some NaN values for O1 velocity. This is a bit unusual as using the same dataset, grid nodes etc, a bctides.inM I created  previously looks quite ok without NaN.

While I will dig into it at some point, I create this issue here for your reference.

Cheers

![Screenshot from 2022-06-30 16-02-54](https://user-images.githubusercontent.com/32722297/176604074-dcfb75d1-8839-40de-9bcd-76e1432744ab.png)

**Comment by wzhengui** [comment]
Thank you, @huyquangtranaus . The error seems to be issue related to interpolation failure. Do you have a grid that I can test to reproduce the error?
