### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by jieAmple** [wzhengui/pylibs#5]
hi @wzhengui 
I follow your usage instruction to install pylibs and have an issue: 
![Screenshot from 2022-12-07 16-05-59](https://user-images.githubusercontent.com/114220970/206122941-6b0f366d-b1e2-4cfe-8ee3-030bcdd77d90.png)
could you help me out?
thanks
jie

**Comment by wzhengui** [comment]
You need to git clone pylib first. Zhengui

**Comment by jieAmple** [comment]
I actually git clone pylibs, but installation still fails. Do you have any suggestions?
________________________________

**Comment by wzhengui** [comment]
I have no clue. Maybe, you can try PYTHONPATH.
