### ISSUE TITLE
Format of region BP file

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [wzhengui/pylibs#6]
@feiye-vims what is the format of the region BP file header? Should the coordinates start at line 4? That seems to be the way you're reading it.

https://github.com/wzhengui/pylibs/blob/0315d502657439f615035669305cb363e06d0a0c/pylib_experimental/pylib_essentials/pylib_essentials/schism_file.py#L1336-L1342

Is it something like
```
! Comment 1
! Comment 2
nsta
x1 y1
x2 y2
...
```

**Comment by feiye-vims** [comment]
the region file's format is like this:

any text  ! first line
1  ! number of regions
3 1 ! nsta, no sure what is the second number
x1 y1
x2 y2
x3 y3

Unlike *.bp files, the second line of a region file specifies the number of regions, which is why the coordinates start from line 4.

**Comment by feiye-vims** [comment]
The code seems only handling the case of a single region, which is acceptable because we always specify only one region in a region file. 

And under such circumstances, your interpretation is correct because the second line is meaningless.

**Comment by SorooshMani-NOAA** [comment]
I see, thank you! So in theory we can have multiple regions (multiple polygons) like this, right? It's just not handling it right now? But the polygons cannot have holes, is that correct?

**Comment by feiye-vims** [comment]
Correct.

**Comment by feiye-vims** [comment]
I followed https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/issues/122, I can use a polygon shapefile or a gpkg to specify the region, which may be better since it has projection information. And you don't need to worry about the region file format which is uncommon outside the SCHISM user group.

Let me know if you prefer this.

**Comment by SorooshMani-NOAA** [comment]
Thanks, I'd definitely prefer a shapefile in this case, it's more straightforward. But for the first iteration I can just use the bp format and later when you add it to the relocate script I can switch to shapefile

**Comment by SorooshMani-NOAA** [comment]
@feiye-vims I just realized the `pylibs` methods accept multiple polygons, so I'll just process the shapefile and pass the list to those method instead of using bpfile. I think that's what you meant and I misunderstood!

**Comment by feiye-vims** [comment]
No you didn't misunderstand, I was going to use a shapefile instead of the region file. But yes, pylibs inside_polygon accepts multiple polygons and the algorithm is very efficient.
